#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "incus"
name = "Incus"
description.en = "Powerful system container and virtual machine manager"
description.fr = "Gestionnaire puissant de conteneurs système et de machines virtuelles"

version = "6.6~ynh1"

maintainers = ["Salamandar"]

[upstream]
license = "Apache-2.0"
website = "https://linuxcontainers.org/incus/"
demo = "https://linuxcontainers.org/incus/try-it/"
admindoc = "https://linuxcontainers.org/incus/docs/main/"
code = "https://github.com/lxc/incus"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = ["amd64"]
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

[resources]
    # Do NOT handle system_user, deb package will
    # [resources.system_user]
    # [resources.install_dir]

    # Do NOT handle /var/lib, deb package will
    # [resources.data_dir]
    # dir = "/var/lib/incus"

    [resources.data_dir]

    [resources.ports]
    main.default = 8443

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"
    main.protected = true

    [resources.apt.extras.incus]
    repo = "https://pkgs.zabbly.com/incus/stable __YNH_DEBIAN_VERSION__ main"
    key = "https://pkgs.zabbly.com/key.asc"
    packages = ["incus", "incus-ui-canonical"]
