#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "incus"
name = "Incus"
description.en = "A powerful system container and virtual machine manager"
description.fr = "Un gestionnaire puissant de conteneurs système et de machines virtuelles"

version = "0.5.1~ynh1"

maintainers = ["Salamandar"]

[upstream]
license = "Apache-2.0"
website = "https://linuxcontainers.org/incus/"

admindoc = "https://linuxcontainers.org/incus/docs/main/"

code = "https://github.com/lxc/incus"
cpe = ""

[integration]
yunohost = '>= 11.2'
architectures = ["amd64"]
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
# FIXME: replace with an **estimate** minimum disk and RAM requirements. e.g. 20M, 400M, 1G... You may have have a look at CI results
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

[resources]

    [resources.system_user]

    [resources.install_dir]
    [resources.data_dir]
    # TODO: incus actual data dir

    [resources.permissions]

    [resources.apt.extras.incus]
    repo = "https://pkgs.zabbly.com/incus/stable bullseye main"
    key = "https://pkgs.zabbly.com/key.asc"
    packages = ["incus"]
