#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP VARIOUS FILES
#=================================================

ynh_backup "/etc/logrotate.d/$app"

ynh_backup "/etc/dnsmasq.d/$app"

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_backup "/var/lib/incus/"

ynh_backup "/var/log/incus/"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
