#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..."

# Use logrotate to manage application logfile(s)
ynh_use_logrotate --logfile="/var/log/incus/incusd.log"

yunohost service add "$app" --description="Incus system container and virtual machine manager" --log="/var/log/incus/incusd.log"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
# ADD A CONFIGURATION
#=================================================
# ynh_script_progression --message="Adding app's configuration file..."

# ynh_add_config --template="" --destination="$install_dir/"

# # FIXME: this should be handled by the core in the future
# # You may need to use chmod 600 instead of 400,
# # for example if the app is expected to be able to modify its own config
# chmod 400 "$install_dir/"
# chown $app:$app "$install_dir/"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last
