#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DNSMASQ CONFIGURATION
#=================================================
ynh_script_progression "Configuring Dnsmasq and NFTables before starting Incus..."

incusbr0_ip=0.0.0.0
_ynh_config_add_dnsmasq
_ynh_config_add_nftables

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Starting and configuring Incus..."

ynh_systemctl --service="$app" --action="start" --log_path="/var/log/incus/incusd.log"

setup_incus

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

yunohost service add "$app" --description="Incus system container and virtual machine manager" --log="/var/log/incus/incusd.log"

ynh_config_add_logrotate "/var/log/incus/incusd.log"

# Dnsmasq is configured again with the proper incusbr0_ip
_set_incus_bridge_ip
_ynh_config_add_dnsmasq

_ynh_config_add_subuid_subgid

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
