#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Starting and configuring Incus..."

ynh_systemctl --service="$app" --action="start" --log_path="/var/log/incus/incusd.log"

setup_incus

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

_set_incus_bridge_ip

yunohost service add "$app" --description="Incus system container and virtual machine manager" --log="/var/log/incus/incusd.log"

ynh_config_add_logrotate "/var/log/incus/incusd.log"

_ynh_add_dnsmasq_config

_ynh_add_subuid_subgid

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
