#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEMD SERVICE
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

yunohost service remove "$app"

network_interfaces_to_remove=$(incus network list -f json | jq '.[] | select(.managed == true) | .name' | tr -d '"')

for network in $network_interfaces_to_remove; do
    ip link delete "$network"
done

ynh_systemctl --service="$app.socket" --action="stop"
ynh_systemctl --service="$app" --action="stop" --log_path="/var/log/incus/incusd.log"

ynh_config_remove_logrotate

_ynh_remove_dnsmasq_config

# Kill dnsmasq and all other process started by incus
kill $(pgrep -u $app)

_ynh_remove_subuid_subgid

ynh_config_remove_nginx

ynh_safe_rm "$data_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
