#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..."

yunohost service remove "$app"

ynh_systemd_action --service_name="$app" --action="start" --log_path="/var/log/incus/incusd.log"

ynh_remove_logrotate

_ynh_remove_dnsmasq_config

_ynh_remove_subuid_subgid

_ynh_firewall_remove_tweak

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
