#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

ynh_config_remove_logrotate

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi
ynh_systemctl --service="$app" --action="stop" --log_path="/var/log/incus/incusd.log"

_ynh_remove_dnsmasq_config

_ynh_remove_subuid_subgid

#=================================================
# REMOVE CONTAINERS
#=================================================

# Remove the data directory if --purge option is used
if [ "${YNH_APP_PURGE:-0}" -eq 1 ]; then
	ynh_script_progression "Removing containers..."
	ynh_safe_rm "/var/lib/incus"
fi

# Remove virtual interface
ip link delete incusbr0

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
