#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

yunohost service add "$app" --description="Incus system container and virtual machine manager" --log="/var/log/incus/incusd.log" $(exposed_ports_if_cluster)

ynh_restore "/etc/logrotate.d/$app"

ynh_restore "/etc/dnsmasq.d/$app"

# Ensure the real bridge IP is configured (overwrite the restored file)
_set_incus_bridge_ip
_ynh_add_dnsmasq_config

_ynh_add_subuid_subgid

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore "/var/log/incus"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading $app's service..."

ynh_systemctl --service="$app" --action="restart" --log_path="/var/log/incus/incusd.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
