#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Restoring system configurations related to $app..." --weight=1

yunohost service add "$app" --description="Incus system container and virtual machine manager" --log="/var/log/incus/incusd.log"

ynh_restore_file --origin_path="/etc/logrotate.d/$app"

ynh_restore_file --origin_path="/etc/dnsmasq.d/$app"

_ynh_add_subuid_subgid

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore_file --origin_path="/var/lib/incus"
ynh_restore_file --origin_path="/var/log/incus"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --last
