#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

yunohost service add "$app" --description="Incus system container and virtual machine manager" --log="/var/log/incus/incusd.log"

ynh_config_add_logrotate

# Maybe IP changed and the upgrade needs to reconfigure it in the settings
_set_incus_bridge_ip
_ynh_add_dnsmasq_config

_ynh_remove_subuid_subgid
_ynh_add_subuid_subgid

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="/var/log/incus/incusd.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
