#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

# Remove legacy hook
if [[ -f "/etc/yunohost/hooks.d/post_iptable_rules/50-${app}" ]]; then
    rm "/etc/yunohost/hooks.d/post_iptable_rules/50-${app}"
fi

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app.socket" --action="stop"
ynh_systemctl --service="$app" --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set_default --key=cluster --value=0

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

yunohost service add "$app" --description="Incus system container and virtual machine manager" --log="/var/log/incus/incusd.log" $(exposed_ports_if_cluster)

ynh_config_add_logrotate "/var/log/incus/incusd.log"

# Maybe IP changed and the upgrade needs to reconfigure it in the settings
_set_incus_bridge_ip
_ynh_config_add_dnsmasq
_ynh_config_add_nftables

_ynh_config_remove_subuid_subgid
_ynh_config_add_subuid_subgid

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --wait_until="Started incus.service" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
